### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by RevRend80** [nwithan8/dizqueTV-scripts#13]
I am trying to do the requirements.txt portion of the setup but get the error: ERROR: Could not find a version that satisfies the requirement dizqueTV (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for dizqueTV (from -r requirements.txt (line 1))

I have tried with the main folder in the home section and in the opt section where my dizquetv container is located.

I am using Ubuntu 18.04

**Comment by nwithan8** [comment]
Run `pip install dizqueTV` manually.
