### ISSUE TITLE
Schedule Creator not working

### ISSUE THREAD

**Issue by RedRaptor10** [nwithan8/dizqueTV-scripts#8]
Trying to run schedule_creator.py and getting this error:

`ModuleNotFoundError: No module named 'dizqueTV.channels'`

I realize there isn't a 'channels.py' file in the 'site-packages\dizqueTV' folder, and schedule_creator.py isn't listed in the README. Is this script deprecated?

**Comment by nwithan8** [comment]
Just hasn't been updated since dizqueTV was refactored.
