### ISSUE TITLE
Add specific movie

### ISSUE THREAD

**Issue by JamesDAdams** [nwithan8/dizqueTV-scripts#9]
Hi,

It would be really nice to have an option to add a specific movie,

I have a discord account which serves as a bot that streams movies 24 hours a day with dizquetv and I would like the user to send a command to add a movie to the dizqueTV channel.

Ex : 

- Commande discord bot choise movie
- DizqueTV-scripts add the movie in specific chanel
- Happy user 😁

Thanks

**Comment by nwithan8** [comment]
Use the main dizqueTV API library to accomplish this.
